export const theme = {
  maxContainerWidth: '1080px',
  darkGray: '#4d4d4d',
  defaultFont: '"Roboto", sans-serif',
  defaultHeaderFont: '"Palanquin", sans-serif',
  defaultFontColor: '#000000',
  defaultFontSize: '24px',
  defaultHeaderColor: '#ffffff',
  defaultInputBackgroundColor: '#f5f5f5',
  defaultMobileFontSize: '18px',
  defaultTransition: 'all 0.2s linear',
  desktopHeaderHeight: '95px',
  disabledColor: '#888888',
  errorColor: '#e44100',
  focusColor: '#0080EE',
  grayText: '#707070',
  lightGray: '#B3B3B3',
  linkColor: '#0080EE',
  mobileHeaderHeight: '70px',
  primaryColor: '#0080EE',
  secondaryColor: '#FDA396',
  hoveredSecondaryColor: '#FA7B6A',
  pressedSecondaryColor: '#FA7B6A',
  lightBackgroundColor: '#EDF6FE',
  borderBlurColor: '#CFE7EE',
  white: '#ffffff',
}
